name: GitHub Actions Demo
on: workflow_dispatch
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - name: Write the status to INFO.txt
        run: python ./src/write_to_file.py --status ${{ job.status }}
      - name: Commit changes to repo
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "update INFO.txt with latest workflow status"
      - name: push changes
        uses: ad-m/github-push-action@master
        with:
            github_token: ${{ secrets.GH_TOKEN }}
            branch: "main"
